#!/bin/bash
#==============================================================================
# Template: Pipeline Chain Submission Script
# Submits multiple dependent Slurm jobs in sequence using --dependency
# Usage: bash scripts/slurm/chain-pipeline.sh
# Generated by: OpenCode Bio — slurm-execution skill
#==============================================================================

set -euo pipefail

# ============ Configuration ============
PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
SLURM_DIR="$PROJECT_DIR/scripts/slurm"
LOG_DIR="$PROJECT_DIR/logs/slurm"

echo "Project: $PROJECT_DIR"
echo "Slurm scripts: $SLURM_DIR"
echo "Logs: $LOG_DIR"
echo ""

# Ensure log directory exists
mkdir -p "$LOG_DIR"

# ============ Submit Pipeline ============

# Step 1: Quality Control
echo "Submitting Step 1: QC..."
JOB_QC=$(sbatch "$SLURM_DIR/01_qc.job" | awk '{print $4}')
echo "  → Job ID: $JOB_QC"

# Step 2: Denoising / Assembly (depends on QC)
echo "Submitting Step 2: Primary Analysis (after QC)..."
JOB_PRIMARY=$(sbatch --dependency=afterok:$JOB_QC "$SLURM_DIR/02_primary.job" | awk '{print $4}')
echo "  → Job ID: $JOB_PRIMARY"

# Step 3: Taxonomy (depends on primary analysis)
echo "Submitting Step 3: Taxonomy (after Primary)..."
JOB_TAX=$(sbatch --dependency=afterok:$JOB_PRIMARY "$SLURM_DIR/03_taxonomy.job" | awk '{print $4}')
echo "  → Job ID: $JOB_TAX"

# Step 4a: Diversity Analysis (depends on taxonomy)
echo "Submitting Step 4a: Diversity (after Taxonomy)..."
JOB_DIV=$(sbatch --dependency=afterok:$JOB_TAX "$SLURM_DIR/04_diversity.job" | awk '{print $4}')
echo "  → Job ID: $JOB_DIV"

# Step 4b: Differential Abundance (depends on taxonomy, parallel with diversity)
echo "Submitting Step 4b: Differential (after Taxonomy)..."
JOB_DIFF=$(sbatch --dependency=afterok:$JOB_TAX "$SLURM_DIR/05_differential.job" | awk '{print $4}')
echo "  → Job ID: $JOB_DIFF"

# ============ Summary ============
echo ""
echo "============================================"
echo "Pipeline submitted successfully!"
echo "============================================"
echo ""
echo "  QC:           $JOB_QC"
echo "  Primary:      $JOB_PRIMARY  (after $JOB_QC)"
echo "  Taxonomy:     $JOB_TAX  (after $JOB_PRIMARY)"
echo "  Diversity:    $JOB_DIV  (after $JOB_TAX)"
echo "  Differential: $JOB_DIFF (after $JOB_TAX)"
echo ""
echo "Dependency graph:"
echo "  QC → Primary → Taxonomy ─┬→ Diversity"
echo "                            └→ Differential"
echo ""
echo "Monitor: squeue -u $(whoami)"
echo "Details: sacct --format=JobID,JobName,State,Elapsed,MaxRSS -j $JOB_QC,$JOB_PRIMARY,$JOB_TAX,$JOB_DIV,$JOB_DIFF"
echo ""

# Save job IDs for later reference
cat > "$LOG_DIR/pipeline-jobs.txt" << EOF
# Pipeline submitted: $(date)
QC=$JOB_QC
PRIMARY=$JOB_PRIMARY
TAXONOMY=$JOB_TAX
DIVERSITY=$JOB_DIV
DIFFERENTIAL=$JOB_DIFF
EOF

echo "Job IDs saved to: $LOG_DIR/pipeline-jobs.txt"
